version: '3'
services:
  crudrest:
   image: crudrestapi:V3
   container_name: crudrest
   restart: always
   depends_on:
     - mysql
   ports:
     - 8080:8080
 
  mysql:
   image: mysql:5.7
   restart: always
   container_name: mysql
   environment:
     MYSQL_ROOT_HOST: "%"
     MYSQL_DATABASE: crud_demo
     MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
   ports:
     - 3306:3306
   secrets:
      - db_root_password
 
secrets:
   db_root_password:
    file: ./secrets/db_root_password.txt
